<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BetterOffensiveInstaller</AssemblyName>
    <RootNamespace>BetterOffensiveInstaller</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>Better Offensive Installer</AssemblyTitle>
    <Product>Better Offensive Installer</Product>
    <Company>Global Retakee</Company>
    <Copyright>Copyright Global Retake</Copyright>
    <Version>1.1.8</Version>
    <FileVersion>1.1.8</FileVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
</Project>
